apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx1
  ports:
  - protocol: TCP
    port: 80         # Cổng mà Service lắng nghe
    targetPort: 80   # Cổng của container Nginx (đã đặt trong `nginx-deployment.yaml`)
    nodePort: 30007  # Cổng bên ngoài mà bạn muốn expose (trong khoảng 30000-32767)
