apiVersion: v1
kind: Service
metadata:
  name: php-backend-service
spec:
  selector:
    app: php-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Chọn một NodePort trong khoảng từ 30000-32767
  type: NodePort
